foundation: OpenNeuroscience
url: https://neuroscience-landscape.com

analytics:
  gtm:
    container_id: G-XZ2BK3C8FR

# Categories (optional)
#
# Categories information is read from the `landscape.yml` data file. The way
# categories are displayed in the web application is computed dynamically based
# on the number of categories and subcategories, as well as the number of items
# on each. Sometimes, however, we may want subcategories to be displayed in a
# specific order within a category (this happens often in the Members category).
# In those cases, it is possible to define that order by overriding a category.
#
# This option can also be used to not display one or more subcategories in the
# landscape. To achieve that, we only need to exclude the subcategory from the
# subcategories list when overriding a category.
#
# categories:
#   - name: <CATEGORY_NAME>
#     subcategories:
#       - <SUBCATEGORY1_NAME>
#       - <SUBCATEGORY2_NAME>
#

colors:
  color1: "rgba(0, 107, 204, 1)" # Buttons, groups, links
  color2: "rgba(255, 0, 170, 1)" # Some highlighted items like filters button, search icon
  color3: "rgba(96, 149, 214, 1)" # Participation stats bars, spinners, modal titles
  color4: "rgba(0, 42, 81, 0.7)" # Categories titles in filters, fieldset in filters modal
  color5: "rgba(1, 107, 204, 0.7)" # Categories and subcategories frames (odd)
  color6: "rgba(0, 42, 81, 0.7)" # Categories and subcategories frames (even)

# Featured items (optional)
#
# This section allows highlighting items that match certain criteria. You can
# define a list of rules and the matching items will be featured in a special
# way in the landscape.
#
# Each rule must define a field for the check as well as the values that will
# trigger a match. At the moment the fields supported are:
#
#   - maturity
#   - subcategory
#
# When a given item's field matches any of the values provided, it will be
# considered a featured item. For each option, it is possible to also define an
# order (which item would be displayed first) and a label for the item.
#
# featured_items:
#   - field: subcategory
#     options:
#       - value: <SUBCATEGORY1_NAME>
#       - value: <SUBCATEGORY2_NAME>
#
featured_items:
  - field: maturity
    options:
      - value: graduated
        order: 1
        label: Major

footer:
  links:
  logo: "https://raw.githubusercontent.com/cncf/artwork/master/other/cncf/horizontal/white/cncf-white.svg"

grid_items_size: medium

# Groups (optional)
#
# In some cases, specially when a landscape contains lots of items, it may be
# interesting to organize them in groups. Each group will be displayed on a
# different tab in the landscape web application. Each entry must contain the
# name of the group (it will be displayed as is) and a list with the categories
# (as defined in the landscape.yml data file) that will be part of this group.
#
# groups:
#   - name: <GROUP_NAME>
#     categories:
#       - <CATEGORY1_NAME>
#       - <CATEGORY2_NAME>
#
groups:
  - name: All categories
    categories:
      - Companies
      - Organizations
      - Laboratories
      - Software
      - Hardware
      - Datasets
      - Books
      - Courses
  - name: Laboratories
    categories:
      - Laboratories

# Header (optional)
#
# This section allows customizing some aspects of the header.
#
# header:
#   links:
#     github: <GITHUB_URL>
#   logo: <LOGO_URL>  # Foundation logo featured on the header
#
header:
  links:
    github: https://github.com/open-neuroscience-foundation
  logo: "https://raw.githubusercontent.com/cncf/artwork/master/other/cncf-landscape/horizontal/color/cncf-landscape-horizontal-color.svg"

# Images (optional)
#
# Urls of some images used in the landscape UI.
#
# images:
#   favicon: <FAVICON_URL>
#   open_graph: <OPEN_GRAPH_IMAGE_URL>
#

# Name of the members category (optional)
#
# Landscapes usually have a special category dedicated to the members of the
# corresponding foundation. It is possible to use any name for that category,
# but it is important that we define it here as there are some special
# operations that depend on it.
#
# members_category: <CATEGORY_NAME>
#

# Screenshot width (optional)
#
# Width of the landscape screenshots automatically generated (in pixels).
# Screenshots won't be taken if this value is not provided.
#
# screenshot_width: <WIDTH_IN_PIXELS>
#
screenshot_width: 1500
# TAGs (optional)
#
# Projects items can specify which TAG owns them in the `landscape.yml` file
# (by using the `tag` field in the `extra` item's section). However, sometimes
# this information is not available at the item level. This configuration
# section provides a mechanism to automatically asign a TAG to projects items
# based on the categories and subcategories they belong to.
#
# For example, we can define that all projects in the category <CATEGORY1> are
# owned by <TAG1>. When the items are processed, the corresponding TAG will be
# set in the items that match the rule defined. The TAG defined at the item
# level always takes precedence, so when it's present it won't be replaced.
#
# NOTE: TAGs names should only use lowercase case letters and hyphens (no
# spaces or other characters), and should not be prefixed with "tag". The
# subcategories field is optional and, when omitted, all of them will be
# included.
#
# tags:
#   <TAG1>:
#     - category: <CATEGORY1>
#       subcategories:
#         - <SUBCATEGORY1>
#         - <SUBCATEGORY2>
#   <TAG2>:
#     - category: <CATEGORY2>
#

# Upcoming event (optional)
#
# This section allows configuring an upcoming event that will be featured on
# the landscape web application. Expired events won't be displayed.
#
# upcoming_event:
#   name: <NAME>         # Event name (required)
#   start: <START_DATE>  # Start date: (required, format: YYYY-MM-DD)
#   end: <END_DATE>      # End date: (required, format: YYYY-MM-DD)
#   banner_url: <URL>    # Event banner image url (required, recommended dimensions: 2400x300)
#   details_url: <URL>   # Event details URL (required)
