foundation: Open Neuroscience Foundation
url: https://neuroscience-landscape.com

analytics:
  gtm:
    container_id: G-XZ2BK3C8FR

colors:
  color1: "rgba(0, 107, 204, 1)" # Buttons, groups, links
  color2: "rgba(255, 0, 170, 1)" # Some highlighted items like filters button, search icon
  color3: "rgba(96, 149, 214, 1)" # Participation stats bars, spinners, modal titles
  color4: "rgba(0, 42, 81, 0.7)" # Categories titles in filters, fieldset in filters modal
  color5: "rgba(1, 107, 204, 0.7)" # Categories and subcategories frames (odd)
  color6: "rgba(0, 42, 81, 0.7)" # Categories and subcategories frames (even)

featured_items:
  - field: maturity
    options:
      - value: graduated
        order: 1
        label: Major

footer:
  links:
    github: https://github.com/open-neuroscience-foundation
  logo: https://raw.githubusercontent.com/open-neuroscience-foundation/.github/1d1273080474ce69a949cb8a5cec0820d0997f8d/logo/onf-light.png
  text: "Projects mentioned may or may not be affiliated with this foundation. Open Neuroscience Foundation. 2024"

grid_items_size: medium

groups:
  - name: All categories
    categories:
      - Companies
      - Organizations
      - Laboratories
      - Software
      - Hardware
      - Datasets
      - Books
      - Courses
  - name: Laboratories
    categories:
      - Laboratories
  - name: Tools
    categories:
      - Software
      - Hardware
      - Datasets
  - name: Learning
    categories:
      - Books
      - Courses

header:
  links:
    github: https://github.com/open-neuroscience-foundation/neuroscience-landscape
  logo: https://raw.githubusercontent.com/open-neuroscience-foundation/.github/1d1273080474ce69a949cb8a5cec0820d0997f8d/logo/onf-dark.png

images:
  favicon: https://raw.githubusercontent.com/open-neuroscience-foundation/neuroscience-landscape/main/logos/onf-light-filled.png
  open_graph: https://raw.githubusercontent.com/open-neuroscience-foundation/neuroscience-landscape/main/logos/onf-light-filled.png
